"use client";
import { useEffect, useMemo, useState } from "react";
import { LayoutDashboard, KanbanSquare, CalendarDays, WalletCards, Users, Plus, Bell, X, ArrowUpRight, CircleCheck, Clock3, AlertTriangle } from "lucide-react";

const stages = ["Junta inicial", "Propuesta", "Desarrollo", "Ajustes", "Entrega", "Finalizado"];
const money = (n:number) => new Intl.NumberFormat("es-MX", {style:"currency", currency:"MXN", maximumFractionDigits:0}).format(n || 0);
const dateText = (value?:string|null) => value ? new Date(`${value}T12:00:00`).toLocaleDateString("es-MX", {day:"numeric", month:"short"}) : "Sin fecha";
const greeting = () => { const h = new Date().getHours(); return h < 12 ? "Buenos días, Vale." : h < 19 ? "Buenas tardes, Vale." : "Buenas noches, Vale."; };
const dueState = (value?:string|null, stage?:string) => { if (!value) return {label:"Sin fecha", tone:"muted"}; if (stage === "Finalizado") return {label:"Entregado", tone:"good"}; const days = Math.ceil((new Date(`${value}T23:59:59`).getTime() - Date.now()) / 86400000); if (days < 0) return {label:`Vencido hace ${Math.abs(days)}d`, tone:"bad"}; if (days === 0) return {label:"Vence hoy", tone:"bad"}; if (days <= 3) return {label:`Vence en ${days}d`, tone:"warn"}; return {label:dateText(value), tone:"muted"}; };
type Data = {clients:any[]; projects:any[]; payments:any[]; notes:any[]};

export default function Dashboard(){
 const [data,setData]=useState<Data>({clients:[],projects:[],payments:[],notes:[]}); const [view,setView]=useState("Resumen"); const [modal,setModal]=useState(""); const [selectedClient,setSelectedClient]=useState<any>(null); const [form,setForm]=useState<any>({}); const [toast,setToast]=useState("");
 const load=()=>fetch("/api/data").then(r=>r.json()).then(setData); useEffect(()=>{load()},[]);
 const clients=data.clients||[], projects=data.projects||[], payments=data.payments||[], notes=data.notes||[]; const clientName=(id:number)=>clients.find(c=>c.id===id)?.name||"Sin cliente";
 const collected=payments.filter(p=>p.status==="Pagado").reduce((s,p)=>s+Number(p.amount),0); const pending=payments.filter(p=>p.status!=="Pagado").reduce((s,p)=>s+Number(p.amount),0); const active=projects.filter(p=>p.stage!=="Finalizado").length; const overdue=projects.filter(p=>dueState(p.deliveryDate,p.stage).tone==="bad").length;
 const monthly=useMemo(()=>Array.from({length:6},(_,i)=>{const d=new Date(); d.setMonth(d.getMonth()-(5-i)); const key=d.toISOString().slice(0,7); return {label:d.toLocaleDateString("es-MX",{month:"short"}).replace(".",""),value:payments.filter(p=>p.status==="Pagado"&&(p.paidAt||"").startsWith(key)).reduce((s,p)=>s+Number(p.amount),0)}}),[payments]); const max=Math.max(...monthly.map(m=>m.value),1);
 const close=()=>{setModal("");setSelectedClient(null);setForm({})};
 const save=async(e:any)=>{e.preventDefault(); const editing=modal.startsWith("editar-"); const type=modal.includes("cliente")?"client":modal.includes("proyecto")?"project":modal.includes("pago")?"payment":"note"; const {id,...changes}=form; const res=await fetch("/api/data",{method:editing?"PATCH":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(editing?{type,id,changes}:{type,...form})}); if(res.ok){close();load();setToast(type==="project"&&!editing?"Proyecto y plan de pagos creados":"Cambios guardados");setTimeout(()=>setToast(""),2200)}};
 const move=async(id:number,stage:string)=>{await fetch("/api/data",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({type:"project",id,changes:{stage}})});load()};
 const markPaid=async(id:number,status:string)=>{await fetch("/api/data",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({type:"payment",id,changes:{status,paidAt:status==="Pagado"?new Date().toISOString().slice(0,10):null}})});load()};
 const edit=async(type:string,id:number,changes:any)=>{await fetch("/api/data",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({type,id,changes})});load();setToast("Cambios guardados");setTimeout(()=>setToast(""),2200)};
 const notify=async()=>{if(!("Notification" in window)||!("serviceWorker" in navigator)){setToast("Tu navegador no soporta alertas");return}const ok=await Notification.requestPermission();if(ok!=="granted"){setToast("Permiso no concedido");return}await navigator.serviceWorker.register("/sw.js");setToast(process.env.NEXT_PUBLIC_VAPID_PUBLIC_KEY?"Alertas push activadas":"PWA instalada; falta configurar VAPID")};
 const selectedProjects=selectedClient?projects.filter(p=>p.clientId===selectedClient.id):[]; const selectedPayments=selectedProjects.flatMap(p=>payments.filter(x=>x.projectId===p.id));
 const nav=[["Resumen",LayoutDashboard],["Clientes",Users],["Kanban",KanbanSquare],["Timeline",CalendarDays],["Finanzas",WalletCards]];
 return <div className="shell"><aside className="sidebar"><div className="brand"><img src="/Logo-TAAK.png" alt="TAAK"/><span>Studio</span></div><nav className="nav">{nav.map(([label,Icon]:any)=><button key={label} className={view===label?"active":""} onClick={()=>setView(label)}><Icon size={16}/><span>{label}</span></button>)}</nav><div className="sidebar-foot">Centro de operaciones<br/>TAAK Studio</div></aside><main className="main"><header className="topbar"><div><div className="eyebrow">{new Date().toLocaleDateString("es-MX",{weekday:"long",day:"numeric",month:"long"})}</div><h1 className="headline">{view==="Resumen"?greeting():view}</h1></div><div className="top-actions"><button className="action subtle" onClick={notify}><Bell size={15}/> Alertas</button><button className="action lime" onClick={()=>setModal("proyecto")}><Plus size={15}/> Nuevo proyecto</button></div></header>
 {view==="Resumen"&&<><Stats collected={collected} pending={pending} active={active} overdue={overdue}/><section className="section"><div className="section-head"><div><div className="section-title">Tu semana</div><div className="muted">Lo que necesita atención primero</div></div><button className="text-button" onClick={()=>setView("Timeline")}>Ver timeline <ArrowUpRight size={14}/></button></div><div className="panel attention">{projects.filter(p=>p.stage!=="Finalizado").filter(p=>dueState(p.deliveryDate,p.stage).tone!=="muted").slice(0,4).map(p=><div className="attention-row" key={p.id}><div className={`attention-icon ${dueState(p.deliveryDate,p.stage).tone}`}><AlertTriangle size={15}/></div><div><b>{p.name}</b><span className="muted">{clientName(p.clientId)} · {dueState(p.deliveryDate,p.stage).label}</span></div><button className="text-button" onClick={()=>{const c=clients.find(c=>c.id===p.clientId);if(c)setSelectedClient(c)}}>Abrir</button></div>)}{!projects.some(p=>p.stage!=="Finalizado"&&dueState(p.deliveryDate,p.stage).tone!=="muted")&&<div className="empty-inline"><CircleCheck size={18}/> Todo está bajo control por ahora.</div>}</div></section><section className="section grid two"><div className="panel"><div className="section-head"><div><div className="section-title">Ingresos</div><div className="muted">Cobrado en los últimos 6 meses</div></div><div className="money">{money(collected)}</div></div><Chart monthly={monthly} max={max}/></div><div className="panel"><div className="section-title">Clientes recientes</div>{clients.slice(-4).reverse().map(c=><ClientRow key={c.id} client={c} projects={projects} onClick={()=>setSelectedClient(c)}/>)}{!clients.length&&<p className="muted">Agrega tu primer cliente.</p>}</div></section></>}
 {view==="Clientes"&&<ClientsView clients={clients} projects={projects} payments={payments} open={setSelectedClient} newClient={()=>setModal("cliente")}/>} 
 {view==="Kanban"&&<KanbanView projects={projects} clientName={clientName} move={move}/>} 
 {view==="Timeline"&&<Timeline projects={projects} clientName={clientName}/>} 
 {view==="Finanzas"&&<Finance payments={payments} projects={projects} monthly={monthly} max={max} collected={collected} pending={pending} clientName={clientName}/>} 
 </main>{selectedClient&&<ClientModal client={selectedClient} projects={selectedProjects} payments={selectedPayments} notes={notes} clientName={clientName} markPaid={markPaid} openEdit={(kind:any,item:any)=>{setForm(item);setModal(`editar-${kind}`);setSelectedClient(null)}} close={()=>setSelectedClient(null)} editClient={()=>{setForm(selectedClient);setModal("editar-cliente");setSelectedClient(null)}} addProject={()=>{setForm({clientId:selectedClient.id});setModal("proyecto");setSelectedClient(null)}} addPayment={()=>{setForm({projectId:selectedProjects[0]?.id});setModal("pago");setSelectedClient(null)}} addNote={()=>{setForm({projectId:selectedProjects[0]?.id});setModal("nota");setSelectedClient(null)}}/>}{modal&&<FormModal kind={modal} clients={clients} projects={projects} form={form} setForm={setForm} save={save} edit={edit} close={close}/>} {toast&&<div className="toast">{toast}</div>}</div>;
}

function Stats({collected,pending,active,overdue}:any){return <section className="grid stats"><div className="stat"><div className="label">Cobrado histórico</div><div className="value">{money(collected)}</div><div className="delta">Ingresos reales</div></div><div className="stat"><div className="label">Por cobrar</div><div className="value">{money(pending)}</div><div className="muted">En planes pendientes</div></div><div className="stat"><div className="label">Proyectos activos</div><div className="value">{active}</div><div className="muted">En operación</div></div><div className="stat"><div className="label">Atención</div><div className="value">{overdue}</div><div className={overdue?"bad-text":"good-text"}>{overdue?"Fechas vencidas":"Todo en orden"}</div></div></section>}
function ClientRow({client,projects,onClick}:any){return <button className="client-row" onClick={onClick}><span className="avatar">{client.name?.slice(0,2).toUpperCase()}</span><span><b>{client.name}</b><small>{projects.filter((p:any)=>p.clientId===client.id).length} proyecto(s)</small></span><ArrowUpRight size={15}/></button>}
function ClientsView({clients,projects,payments,open,newClient}:any){return <section className="section"><div className="section-head"><div><div className="section-title">Cartera de clientes</div><div className="muted">Cada cliente abre su operación completa.</div></div><button className="action lime" onClick={newClient}><Plus size={15}/> Nuevo cliente</button></div><div className="client-grid">{clients.map((c:any)=><button className="client-card" key={c.id} onClick={()=>open(c)}><div className="client-card-head"><span className="avatar large">{c.name.slice(0,2).toUpperCase()}</span><ArrowUpRight size={17}/></div><h3>{c.name}</h3><p>{c.email||"Sin correo registrado"}</p><div className="client-meta"><span>{projects.filter((p:any)=>p.clientId===c.id).length} proyectos</span><span>{money(payments.filter((pay:any)=>projects.some((p:any)=>p.clientId===c.id&&p.id===pay.projectId)&&pay.status==="Pagado").reduce((s:number,p:any)=>s+Number(p.amount),0))}</span></div></button>)}{!clients.length&&<div className="empty-state"><Users size={28}/><b>Aún no tienes clientes</b><span>Empieza agregando el primero.</span><button className="action lime" onClick={newClient}>Agregar cliente</button></div>}</div></section>}
function KanbanView({projects,clientName,move}:any){return <section className="section"><div className="section-head"><div><div className="section-title">Flujo de proyectos</div><div className="muted">Arrastra cualquier tarjeta a cualquier etapa.</div></div></div><div className="kanban">{stages.map(stage=><Lane key={stage} stage={stage} projects={projects.filter((p:any)=>p.stage===stage)} allProjects={projects} clientName={clientName} move={move}/>)}</div></section>}
function Lane({stage,projects,allProjects,clientName,move}:any){return <div className="lane" onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();const id=Number(e.dataTransfer.getData("project"));const p=allProjects.find((x:any)=>x.id===id);if(p&&p.stage!==stage)move(p.id,stage)}}><div className="lane-title">{stage}<span className="count">{projects.length}</span></div>{projects.map((p:any)=><div className="project-card" draggable onDragStart={e=>e.dataTransfer.setData("project",String(p.id))} key={p.id}><strong>{p.name}</strong><small>{clientName(p.clientId)}</small><span className={`due ${dueState(p.deliveryDate,p.stage).tone}`}><Clock3 size={11}/> {dueState(p.deliveryDate,p.stage).label}</span><span className="chip">{p.internalStatus}</span></div>)}</div>}
function Timeline({projects,clientName}:any){return <section className="section panel"><div className="section-title">Timeline de entregas</div><p className="muted">Semana de desarrollo · semana de ajustes</p>{projects.sort((a:any,b:any)=>(a.deliveryDate||"9").localeCompare(b.deliveryDate||"9")).map((p:any)=><div className="timeline-item" key={p.id}><div className="date">{dateText(p.startDate)}</div><div><b>{p.name}</b><div className="muted">{clientName(p.clientId)} · avance {dateText(p.advanceDate)} · entrega {dueState(p.deliveryDate,p.stage).label}</div></div></div>)}{!projects.length&&<p className="muted">Agrega un proyecto para ver su timeline.</p>}</section>}
function Finance({payments,projects,monthly,max,collected,pending,clientName}:any){return <section className="section grid two"><div className="panel"><div className="section-title">Ingresos por mes</div><Chart monthly={monthly} max={max}/></div><div className="panel"><div className="section-title">Resumen financiero</div><p className="muted">Total cobrado</p><div className="money">{money(collected)}</div><hr/><p className="muted">Pendiente de cobro</p><div className="money">{money(pending)}</div></div><div className="panel" style={{gridColumn:"1/-1"}}><div className="section-title">Pagos y vencimientos</div>{payments.length?payments.map((p:any)=><div className="payment-row" key={p.id}><div><b>{p.label}</b><span className="muted">{clientName(projects.find((x:any)=>x.id===p.projectId)?.clientId)} · {p.dueDate?`vence ${dateText(p.dueDate)}`:"sin fecha"}</span></div><strong className={p.status==="Pagado"?"good-text":"warn-text"}>{money(p.amount)} · {p.status}</strong></div>):<p className="muted">Todavía no hay pagos registrados.</p>}</div></section>}
function Chart({monthly,max}:any){return <div className="chart">{monthly.map((m:any)=><div className="month" key={m.label}><i style={{height:`${Math.max(8,m.value/max*110)}px`}}></i>{m.label}<br/><b>{money(m.value)}</b></div>)}</div>}
function ClientModal({client,projects,payments,notes,markPaid,openEdit,editClient,close,addProject,addPayment,addNote}:any){const paid=payments.filter((p:any)=>p.status==="Pagado").reduce((s:number,p:any)=>s+Number(p.amount),0);const pending=payments.filter((p:any)=>p.status!=="Pagado").reduce((s:number,p:any)=>s+Number(p.amount),0);return <div className="overlay"><div className="drawer"><button className="close" onClick={close}><X size={18}/></button><div className="drawer-head"><span className="avatar large">{client.name.slice(0,2).toUpperCase()}</span><div><div className="eyebrow">Cliente</div><h2>{client.name}</h2><p>{client.email||"Sin correo registrado"}</p></div><button className="text-button" onClick={editClient}>Editar</button></div><div className="drawer-stats"><div><small>Cobrado</small><b>{money(paid)}</b></div><div><small>Proyectos</small><b>{projects.length}</b></div><div><small>Falta por cobrar</small><b>{money(pending)}</b></div></div><div className="drawer-actions"><button onClick={addProject}><Plus size={14}/> Proyecto</button><button onClick={addPayment}><WalletCards size={14}/> Pago</button><button onClick={addNote}><Plus size={14}/> Nota</button></div><h3>Proyectos</h3>{projects.map((p:any)=><div className="detail-project" key={p.id}><div><span><b>{p.name}</b> <button className="mini-edit" onClick={()=>openEdit("proyecto",p)}>Editar</button></span><span className="muted">{p.stage} · {dueState(p.deliveryDate,p.stage).label}</span></div><div className="installments">{payments.filter((x:any)=>x.projectId===p.id).map((pay:any)=><div key={pay.id} className={pay.status==="Pagado"?"installment paid":"installment"}><button onClick={()=>markPaid(pay.id,pay.status==="Pagado"?"Pendiente":"Pagado")}><span>{pay.label}</span><strong>{money(pay.amount)}</strong><small>{pay.status==="Pagado"?"Pagado · click para desmarcar":"Pendiente · click para marcar"}</small></button><button className="mini-edit" onClick={()=>openEdit("pago",pay)}>Editar pago</button></div>)}</div></div>)}<h3>Notas internas</h3>{notes.filter((n:any)=>projects.some((p:any)=>p.id===n.projectId)).map((n:any)=><div className="note-row" key={n.id}>{n.body}<button className="mini-edit" onClick={()=>openEdit("nota",n)}>Editar</button></div>)}{!notes.length&&<p className="muted">No hay notas todavía.</p>}</div></div>}
function FormModal({kind,clients,projects,form,setForm,save,close}:any){const editing=kind.startsWith("editar-");const base=editing?kind.replace("editar-",""):kind;const title=editing?`Editar ${base}`:base==="cliente"?"Nuevo cliente":base==="proyecto"?"Nuevo proyecto":base==="pago"?"Registrar pago":"Nueva nota";const update=(key:string)=>(e:any)=>setForm({...form,[key]:e.target.value});return <div className="overlay"><form onSubmit={save} className="form-modal"><button type="button" className="close" onClick={close}><X size={18}/></button><div className="section-title">{title}</div>{base==="cliente"&&<><Field label="NOMBRE" required value={form.name||""} onChange={update("name")}/><Field label="EMAIL" type="email" value={form.email||""} onChange={update("email")}/><Field label="TELÉFONO" value={form.phone||""} onChange={update("phone")}/></>}{base==="proyecto"&&<><Select label="CLIENTE" required value={form.clientId||""} onChange={update("clientId")} options={clients.map((c:any)=>[c.id,c.name])}/><Field label="NOMBRE DEL PROYECTO" required value={form.name||""} onChange={update("name")}/><Field label="VALOR TOTAL (MXN)" type="number" min="0" value={form.budget||""} onChange={update("budget")}/>{!editing&&<div className="form-hint"><CircleCheck size={14}/> Se crea automáticamente un plan 50/50: anticipo y contraentrega.</div>}<div className="date-pair"><Field label="INICIO" type="date" value={form.startDate||""} onChange={update("startDate")}/><Field label="AVANCE" type="date" value={form.advanceDate||""} onChange={update("advanceDate")}/></div><Field label="ENTREGA FINAL" type="date" value={form.deliveryDate||""} onChange={update("deliveryDate")}/><Select label="ESTADO" value={form.stage||"Junta inicial"} onChange={update("stage")} options={stages.map(s=>[s,s])}/><Field label="ESTADO INTERNO" value={form.internalStatus||"En diseño"} onChange={update("internalStatus")}/></>}{base==="pago"&&<><Select label="PROYECTO" required value={form.projectId||""} onChange={update("projectId")} options={projects.map((p:any)=>[p.id,p.name])}/><Field label="CONCEPTO" placeholder="Anticipo, contraentrega…" value={form.label||""} onChange={update("label")}/><Field label="MONTO (MXN)" type="number" required value={form.amount||""} onChange={update("amount")}/><Field label="FECHA LÍMITE" type="date" value={form.dueDate||""} onChange={update("dueDate")}/><Select label="ESTADO" value={form.status||"Pagado"} onChange={update("status")} options={[["Pagado","Pagado"],["Pendiente","Pendiente"]]}/></>}{base==="nota"&&<><Select label="PROYECTO" required value={form.projectId||""} onChange={update("projectId")} options={projects.map((p:any)=>[p.id,p.name])}/><div className="field"><label>NOTA INTERNA</label><textarea required rows={4} value={form.body||""} onChange={update("body")} placeholder="Ej. NDA firmado…"/></div></>}<button className="action lime" style={{marginTop:10}}>Guardar cambios</button></form></div>}
function Field(p:any){const {label,...input}=p;return <div className="field"><label>{label}</label><input {...input}/></div>} function Select({label,options,...p}:any){return <div className="field"><label>{label}</label><select {...p}><option value="">Seleccionar…</option>{options.map((o:any)=><option value={o[0]} key={o[0]}>{o[1]}</option>)}</select></div>}
