"use client";
import { useEffect, useMemo, useState } from "react";
import { LayoutDashboard, KanbanSquare, CalendarDays, WalletCards, Plus, Bell, X } from "lucide-react";
const stages = ["Junta inicial", "Propuesta", "Desarrollo", "Ajustes", "Entrega", "Finalizado"];
const money = (n:number) => new Intl.NumberFormat("es-MX", {style:"currency", currency:"MXN", maximumFractionDigits:0}).format(n || 0);
type Data = { clients:any[]; projects:any[]; payments:any[]; notes:any[] };
export default function Dashboard(){
 const [data,setData]=useState<Data>({clients:[],projects:[],payments:[],notes:[]}); const [view,setView]=useState("Resumen"); const [modal,setModal]=useState(""); const [form,setForm]=useState<any>({}); const [toast,setToast]=useState("");
 const load=()=>fetch("/api/data").then(r=>r.json()).then(setData); useEffect(()=>{load()},[]);
 const projects=data.projects||[], clients=data.clients||[], payments=data.payments||[]; const collected=payments.filter(p=>p.status==="Pagado").reduce((s,p)=>s+Number(p.amount),0); const pending=payments.filter(p=>p.status!=="Pagado").reduce((s,p)=>s+Number(p.amount),0); const total=projects.reduce((s,p)=>s+Number(p.budget),0); const clientName=(id:number)=>clients.find(c=>c.id===id)?.name||"Sin cliente";
 const save=async(e:any)=>{e.preventDefault();const type=modal==="cliente"?"client":modal==="proyecto"?"project":modal==="pago"?"payment":"note";await fetch("/api/data",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({type,...form})});setModal("");setForm({});load();setToast("Guardado");setTimeout(()=>setToast(""),2000)};
 const move=async(p:any,stage:string)=>{await fetch("/api/data",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({type:"project",id:p.id,changes:{stage}})});load()};
 const monthly=useMemo(()=>Array.from({length:6},(_,i)=>{const d=new Date();d.setMonth(d.getMonth()-(5-i));const key=d.toISOString().slice(0,7);return {label:d.toLocaleDateString("es-MX",{month:"short"}).replace(".",""),value:payments.filter(p=>p.status==="Pagado"&&(p.paidAt||"").startsWith(key)).reduce((s,p)=>s+Number(p.amount),0)}}),[payments]); const max=Math.max(...monthly.map(m=>m.value),1);
 const notify=async()=>{if(!("Notification" in window)||!("serviceWorker" in navigator)){setToast("Tu navegador no soporta alertas");return}const ok=await Notification.requestPermission();if(ok!=="granted"){setToast("Permiso no concedido");return}const reg=await navigator.serviceWorker.register("/sw.js");const key=process.env.NEXT_PUBLIC_VAPID_PUBLIC_KEY;if(key){const raw=atob(key.replace(/-/g,"+").replace(/_/g,"/"));const sub=await reg.pushManager.subscribe({userVisibleOnly:true,applicationServerKey:Uint8Array.from(raw,c=>c.charCodeAt(0))});await fetch("/api/push/subscribe",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(sub)});setToast("Alertas push activadas")}else setToast("PWA instalada; falta configurar VAPID")};
 return <div className="shell"><aside className="sidebar"><div className="brand">TAAK<span>·</span>CRM</div><nav className="nav">{[["Resumen",LayoutDashboard],["Kanban",KanbanSquare],["Timeline",CalendarDays],["Finanzas",WalletCards]].map(([label,Icon]:any)=><button key={label} className={view===label?"active":""} onClick={()=>setView(label)}><Icon size={17} style={{verticalAlign:"middle",marginRight:10}}/>{label}</button>)}</nav><div className="sidebar-foot">Estudio de diseño web<br/>Hecho para trabajar mejor.</div></aside><main className="main"><header className="topbar"><div><div className="eyebrow">Centro de operaciones</div><h1 className="headline">{view==="Resumen"?"Buenos días, TAAK.":view}</h1></div><div style={{display:"flex",gap:8}}><button className="action" onClick={notify}><Bell size={15}/> Avisarme</button><button className="action lime" onClick={()=>setModal("proyecto")}><Plus size={15}/> Nuevo</button></div></header>
 {view==="Resumen"&&<><Stats collected={collected} pending={pending} total={total} count={clients.length}/><section className="section"><div className="section-head"><div className="section-title">Pulso financiero</div><button className="muted" onClick={()=>setView("Finanzas")}>Ver detalle →</button></div><div className="panel"><div className="money">{money(collected)} <span className="muted">cobrado en 6 meses</span></div><Chart monthly={monthly} max={max}/></div></section></>}
 {(view==="Resumen"||view==="Kanban")&&<section className="section"><div className="section-head"><div className="section-title">Proyectos</div><button className="action lime" onClick={()=>setModal("proyecto")}><Plus size={14}/> Proyecto</button></div><div className="kanban">{stages.map(stage=><Lane key={stage} stage={stage} projects={projects.filter(p=>p.stage===stage)} clientName={clientName} move={move}/>)}</div></section>}
 {view==="Timeline"&&<section className="section panel"><div className="section-title">Ritmo de entregas</div><p className="muted">Desarrollo en 1 semana · ajustes en 1 semana</p>{projects.length?projects.map(p=><div className="timeline-item" key={p.id}><div className="date">{p.startDate||"Por definir"}</div><div><b>{p.name}</b><div className="muted">{clientName(p.clientId)} · avance {p.advanceDate||"por definir"} · entrega {p.deliveryDate||"por definir"}</div></div></div>):<p className="muted">Agrega un proyecto para ver su timeline.</p>}</section>}
 {view==="Finanzas"&&<section className="section grid two"><div className="panel"><div className="section-title">Ingresos por mes</div><Chart monthly={monthly} max={max}/></div><div className="panel"><div className="section-title">Resumen del negocio</div><p className="muted">Total cobrado</p><div className="money">{money(collected)}</div><hr/><p className="muted">Pendiente de cobro</p><div className="money">{money(pending)}</div></div><div className="panel" style={{gridColumn:"1/-1"}}><div className="section-title">Pagos recientes</div>{payments.length?payments.slice(0,8).map(p=><div key={p.id} style={{display:"flex",justifyContent:"space-between",padding:"13px 0",borderBottom:"1px solid var(--line)"}}><span>{p.label} · {money(p.amount)}</span><span className={p.status==="Pagado"?"delta":"muted"}>{p.status}</span></div>):<p className="muted">Todavía no hay pagos registrados.</p>}</div></section>}
 {view==="Resumen"&&<section className="section grid two"><div className="panel"><div className="section-title">Próximas entregas</div>{projects.filter(p=>p.deliveryDate).map(p=><div key={p.id} style={{display:"flex",justifyContent:"space-between",padding:"13px 0",borderBottom:"1px solid var(--line)"}}><span><b>{p.name}</b><br/><span className="muted">{clientName(p.clientId)}</span></span><span className="date">{p.deliveryDate}</span></div>)}{!projects.some(p=>p.deliveryDate)&&<p className="muted">No hay fechas próximas.</p>}</div><div className="panel"><div className="section-title">Acciones rápidas</div><button className="action" style={{width:"100%",marginTop:18}} onClick={()=>setModal("cliente")}>Agregar cliente</button><button className="action" style={{width:"100%",marginTop:9,background:"#eef0ff",color:"#4f5fd2"}} onClick={()=>setModal("pago")}>Registrar pago</button><button className="action" style={{width:"100%",marginTop:9,background:"#f2f2ed",color:"#222"}} onClick={()=>setModal("nota")}>Escribir nota</button></div></section>}
 </main>{modal&&<Modal kind={modal} clients={clients} projects={projects} form={form} setForm={setForm} save={save} close={()=>setModal("")}/>} {toast&&<div style={{position:"fixed",bottom:20,left:"50%",transform:"translateX(-50%)",background:"#171918",color:"white",padding:"12px 18px",borderRadius:9}}>{toast}</div>}</div>;
}
function Stats({collected,pending,total,count}:any){return <section className="grid stats"><div className="stat"><div className="label">Cobrado histórico</div><div className="value">{money(collected)}</div><div className="delta">Todos los clientes</div></div><div className="stat"><div className="label">Por cobrar</div><div className="value">{money(pending)}</div><div className="muted">Pagos pendientes</div></div><div className="stat"><div className="label">Valor contratado</div><div className="value">{money(total)}</div><div className="muted">Proyectos activos</div></div><div className="stat"><div className="label">Clientes</div><div className="value">{count}</div><div className="muted">En tu cartera</div></div></section>}
function Chart({monthly,max}:any){return <div className="chart">{monthly.map((m:any)=><div className="month" key={m.label}><i style={{height:`${Math.max(8,m.value/max*110)}px`}}></i>{m.label}<br/><b>{money(m.value)}</b></div>)}</div>}
function Lane({stage,projects,clientName,move}:any){return <div className="lane" onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();const id=Number(e.dataTransfer.getData("project"));const p=projects.find((x:any)=>x.id===id);if(p)move(p,stage)}}><div className="lane-title">{stage}<span className="count">{projects.length}</span></div>{projects.map((p:any)=><div className="project-card" draggable onDragStart={e=>e.dataTransfer.setData("project",String(p.id))} key={p.id}><strong>{p.name}</strong><small>{clientName(p.clientId)}</small><small>Entrega: {p.deliveryDate||"sin fecha"}</small><span className="chip">{p.internalStatus}</span><div style={{display:"flex",gap:4,marginTop:8}}>{stages.filter(s=>s!==stage).slice(0,2).map(s=><button key={s} className="muted" onClick={()=>move(p,s)}>→ {s}</button>)}</div></div>)}</div>}
function Modal({kind,clients,projects,form,setForm,save,close}:any){const title=kind==="cliente"?"Nuevo cliente":kind==="proyecto"?"Nuevo proyecto":kind==="pago"?"Registrar pago":"Nueva nota";const update=(key:string)=>(e:any)=>setForm({...form,[key]:e.target.value});return <div style={{position:"fixed",inset:0,background:"#17191880",display:"grid",placeItems:"center",zIndex:3}}><form onSubmit={save} className="panel" style={{width:"min(440px,calc(100% - 30px))",position:"relative"}}><button type="button" onClick={close} style={{position:"absolute",right:15,top:15,background:"none"}}><X size={18}/></button><div className="section-title">{title}</div>{kind==="cliente"&&<><Field label="NOMBRE" required onChange={update("name")}/><Field label="EMAIL (opcional)" type="email" onChange={update("email")}/></>}{kind==="proyecto"&&<><Select label="CLIENTE" required onChange={update("clientId")} options={clients.map((c:any)=>[c.id,c.name])}/><Field label="NOMBRE DEL PROYECTO" required onChange={update("name")}/><Field label="VALOR TOTAL (MXN)" type="number" onChange={update("budget")}/><Field label="FECHA DE ENTREGA" type="date" onChange={update("deliveryDate")}/></>}{kind==="pago"&&<><Select label="PROYECTO" required onChange={update("projectId")} options={projects.map((p:any)=>[p.id,p.name])}/><Field label="CONCEPTO" placeholder="Anticipo, contraentrega…" onChange={update("label")}/><Field label="MONTO (MXN)" type="number" required onChange={update("amount")}/><Select label="ESTADO" onChange={update("status")} options={[["Pagado","Pagado"],["Pendiente","Pendiente"]]}/></>}{kind==="nota"&&<><Select label="PROYECTO" required onChange={update("projectId")} options={projects.map((p:any)=>[p.id,p.name])}/><div className="field"><label>NOTA INTERNA</label><textarea required rows={4} onChange={update("body")} placeholder="Ej. NDA firmado…"/></div></>}<button className="action lime" style={{marginTop:10}}>Guardar</button></form></div>}
function Field(p:any){return <div className="field"><label>{p.label}</label><input {...p}/></div>} function Select({label,options,...p}:any){return <div className="field"><label>{label}</label><select {...p}><option value="">Seleccionar…</option>{options.map((o:any)=><option value={o[0]} key={o[0]}>{o[1]}</option>)}</select></div>}
